[package]
name = "cg"
version = "0.1.0"
authors = ["Ciro S. Costa <cscosta@pivotal.io>"]
edition = "2018"
description = "Throwing chickens into the system"

[dependencies]
clap = "2.0"
num_cpus = "1.0"
libc = "0.2"
rand = "0.6"
nix = "0.13.0"
pretty-bytes = "0.2.2"
