[package]
name = "cg"
version = "0.1.0"
authors = ["Ciro S. Costa <cscosta@pivotal.io>"]
edition = "2018"
description = "Throwing chickens into the system"

[dependencies]
clap = "2.0"
num_cpus = "1.0"
